// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9qtzggB4lQ1G6W6HefT1QV9L36rqJVJc',
    appId: '1:499869252845:web:d7da87596552786f1820e4',
    messagingSenderId: '499869252845',
    projectId: 'graduation-project-a1c54',
    authDomain: 'graduation-project-a1c54.firebaseapp.com',
    storageBucket: 'graduation-project-a1c54.appspot.com',
    measurementId: 'G-QN63N32ESF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYr1sitL9krKY_nz3G8Ub-qqEh4tRi0EI',
    appId: '1:499869252845:android:d793d7a04f461bb31820e4',
    messagingSenderId: '499869252845',
    projectId: 'graduation-project-a1c54',
    storageBucket: 'graduation-project-a1c54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9J7FKYVI9khpgZ2rh-4-QB6zGZz3iuuI',
    appId: '1:499869252845:ios:d754f12535b813151820e4',
    messagingSenderId: '499869252845',
    projectId: 'graduation-project-a1c54',
    storageBucket: 'graduation-project-a1c54.appspot.com',
    iosClientId: '499869252845-l10klvsn0olklntegdmkutlatq7s3kri.apps.googleusercontent.com',
    iosBundleId: 'com.example.gproject',
  );
}
